group: deprecated-2017Q4

dist: xenial

os: linux
  
language: java

jdk: openjdk8
  
cache:
  directories:
    $HOME/.m2

after_success: mvn clean test

notifications:
  email: false

# for skipping tests
#install: true
  
#after_success: mvn package -DskipTests

#services:
  #- mysql
  
#before_install:
  # - mysql -u root --password="" < sql/dump.sql
 
#before_script:
  #- mysql -e 'create database food_application;'
  #- mysql -u root food_application < sql/dump.sql
