group: deprecated-2017Q4
dist: xenial
os:
  linux
language: java
jdk:
  openjdk8
cache:
  directories:
    $HOME/.m2
install:
  mvn clean install -Dgpg.skip=true
after_success:
  mvn package -DskipTests
language: ruby
rvm:
 2.2
 jruby
