group: deprecated-2017Q4
dist: trusty
os:
  - linux
language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
cache:
  directories:
    -$HOME/.m2
install:
  - mvn clean install -Dgpg.skip=true
after_success:
  - mvn package -DskipTests
