group: deprecated-2017Q4

dist: bionic

os: linux
  
language: generic

jdk: openjdk13
  
cache:
  directories:
    $HOME/.m2

script: - mvn clean test
  
install:
- mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
