group: deprecated-2017Q4

dist: xenial

os: linux
  
language: generic

jdk: openjdk8
  
cache:
  directories:
    $HOME/.m2

install:
- mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V


script: - mvn clean test
