group: deprecated-2017Q4

dist: xenial

os: linux
  
language: generic

jdk: openjdk8
  
cache:
  directories:
    $HOME/.m2

# for skipping tests
install: true
  
after_success: mvn package -DskipTests

services:
  - mysql
  
before_install:
  - mysql -u root --password="root" < sql/dump.sql
