group: deprecated-2017Q4

dist: bionic

os: linux
  
language: java

jdk: openjdk13
  
cache:
  directories:
    $HOME/.m2

script: - mvn clean test

notifications:
  email: true
  
install:
- mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
