apiVersion: v1
kind: ConfigMap
metadata:
  name: smarttrip-config
  namespace: smarttrip
data:
  DB_URL: "jdbc:postgresql://postgres.smarttrip.svc.cluster.local:5432/smarttrip"
  DB_USER: "smarttrip"
  REDIS_HOST: "redis.smarttrip.svc.cluster.local"
  REDIS_PORT: "6379"
  JWT_ISSUER: "https://api.smarttrip.example/user"

